site_name: "Basic Formal Ontology"
repo_url: https://github.com/BFO-Organization/
edit_uri: '?query=root/BFO-Organization/docs/'
theme:
  name: readthedocs
nav:
  - Home: index.md
  - Preface: preface.md
  - Introduction: introduction.md
  - Basic Formal Ontology: basic-formal-ontology.md
  - Scope: scope.md
  - Conformance: conformance.md
  - Normative Reference: normative-reference.md
  - Terms and Definitions: terms-and-definitions.md
  - Conventions: conventions.md
  - BFO-Core: bfo-core.md
  - Temporalized Relations Extension: temporalized-relations-extensions.md
  - Stasis Extension: stasis-extension.md
  - Temporal Annotation Extension: temporal-annotation-extension.md
  - Mapping Extensions: mapping-extensions.md
  - Important Extensions: important-extensions.md
  - Summary: summary.md
  - Annex A - Design Patterns: design-patterns.md
  - Annex B - SPARQL Quality Control: sparql-quality-control.md
  - Annex C - SHACL Quality Control: shacl-quality-control.md

