site_name: "ICBO-2022: International Conference on Biomedical Ontology"
repo_url: https://github.com/ICBO-conference/icbo2022/
edit_uri: '?query=root/icbo2022/docs/'
theme:
  name: readthedocs
nav:
  - Home: index.md
  - Call for Submissions: call-for-submissions.md
  - Keynote Speakers: keynote-speakers.md
  - Journal of Biomedical Semantics ICBO Thematic Series: submit-jbms-icbo.md
  - Workshops & Tutorials: workshops-and-tutorials.md
  - Workshop Publication Requirements: workshop-publication-requirements.md
  - Michigan Week of Ontology and Semantic Web: michigan-week-of-ontology-and-semantic-web.md 
  - CCBOT 2022 (joint conference): ccbot2022.md 
  - Registration: icbo-registration.md
  - ICBO Hotel Options: icbo-hotels.md
  - Travel to ICBO:  icbo-travel.md
  - Sunday Morning Carpool: sunday-morning-carpool.md
  - Schedule: icbo-schedule.md
  - Papers and Poster Abstracts: papers-and-poster-abstracts.md
  - Poster Awards: poster-awards.md
  - Conference Photos: conference-photos.md
  - Contact Information: contact-information.md
  - Co-organizers: co-organizers.md
  - Program Committee: program-committee.md
